theme: jekyll-theme-cayman
title: CoronaSurveys
description: Monitoring the Incidence of COVID-19 via Open Polls <br> <br> The following results present our estimations on the incidence of COVID-19 in the countries from which we have enough information. You can help by regularly completing the survey below. <br> <br> <img src="https://raw.githubusercontent.com/AugustoGarcia/Coronasurveys-web/master/assets/logo.jpg" height="200" width="600"> 
github:
  is_project_page: false
