theme: jekyll-theme-cayman
title: CoronaSurveys
description: Monitoring the Incidence of COVID-19 via Open Polls <br> <br> The following results present our estimations on the incidence of COVID-19 in the countries from which we have enough information. You can help by regularly completing the survey below. <br> <img src="https://github.com/AugustoGarcia/Coronasurveys-web/blob/master/assets/logo.jpg" height="300" width="300"> 
github:
  is_project_page: false
